<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Promise</title>
  </head>
  <body>
    <script>
      // 1st promise

        new Promise((resolve, reject) => {
          setTimeout(() => {
            console.log("Async task");
            resolve();
          }, 1000);
        }).then(() => {
          console.log("Resolved succesfully");
        });

      //2nd promise declearetion method
        new Promise((resolve,reject)=>{
           setTimeout(() => {
              console.log('SetTime out executed after 1sec');
              resolve({
                  userName:'Pappu Kumar',
                  email:'pk7248043@gmail.com',
                  DOB:'11/08/2002'
              });
           }, 1000);
        }).then((user)=>{
              console.log(user);
        })

      // 3rd Method to consume promises
      new Promise((resolve,reject)=>{
           setTimeout(() => {
              console.log('SetTime out executed after 1sec');
             let err=false;
             if(!err){
              resolve({
                  userName:'Pappu Kumar',
                  email:'pk7248043@gmail.com',
                  DOB:'11/08/2002'
              });
             }else{
              reject('Error : Somthing went wrong')
             }
           }, 1000);
        }).then((user)=>{
              console.log(`User DOB : ${user.DOB}`);
        }).catch((error)=>{
            console.log(error);
        }).finally(()=>console.log('Finaly executed either promise is resolved or rejected'))

      // Next method to consume promises
      const nextPromise=new Promise((resolve, reject) => {
        setTimeout(() => {
          console.log("SetTime out executed after 1sec");
          let err = false;
          if (!err) {
            resolve({
              userName: "Pappu Kumar",
              email: "pk7248043@gmail.com",
              DOB: "11/08/2002",
            });
          } else {
            reject("Error : Somthing went wrong");
          }
        }, 1000);
      })
       
      async function consumeNextPromise(){
        try {
            const response=await nextPromise
            console.log(response.DOB);
        } catch (error) {
            console.log(error);
        }
      }
      consumeNextPromise();


    // Try catch syntax
    async function getAllUsers(){
        try {
            const response=await fetch('https://jsonplaceholder.typicode.com/users');
            const data=await response.json();
            console.log(data);
        } catch (error) {
            console.log('Error generated : ', error);
        }
    }
    getAllUsers()


    // fetch syntax
    fetch('https://jsonplaceholder.typicode.com/users')
    .then((response)=>{
        return response.json();
    }).then((data)=>{
       console.log(data);
    }).catch((error)=>{
        console.log(error);
    })
    </script>
  </body>
</html>
